### ISSUE TITLE
Version 3.0 doesn't reconnect after error

### ISSUE THREAD

**Issue by jacekpaszkowski** [lukas-hetzenecker/home-assistant-remote#78]
Hello,

i got this error in logs:

```
2020-12-08 17:24:25 ERROR (MainThread) [custom_components.remote_homeassistant] failed to fetch instance info
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.1.246', 8123)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 366, in _async_instance_get_info
    return await async_get_discovery_info(
  File "/config/custom_components/remote_homeassistant/rest_api.py", line 38, in async_get_discovery_info
    async with session.get(url, headers=headers) as resp:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1124, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 527, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 541, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 898, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1057, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1026, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 981, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio-slave1-wifi.lan:8123 ssl:default [Connect call failed ('192.168.1.246', 8123)]
2020-12-08 17:24:25 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 399, in async_connect
    if not (info or _async_instance_id_match(info)):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 381, in _async_instance_id_match
    if info["uuid"] != self._entry.unique_id:
TypeError: 'NoneType' object is not subscriptable
```

Then there is no reconnection with slave device. Have to reload integration or restart HA

**Comment by postlund** [comment]
I will take a look later tonight.

**Comment by jaym25** [comment]
These are changes I have been using on the previous version, 2.3 that have kept the connection very stable through various disconnects.  There are several modifications on how it senses disconnects and how it treats them.  One item in particular is the remove entities variable which does not remove the entities on certain short-term disconnects.  I have not examined the new 3.0 code, so I'm sure this can no longer be pasted as a replacement for the lines identified below, but the extra connection checks and resolutions can be migrated.  Hope this helps:

starting with line 153 thru "async def _init(self):"
It stays connected for short interruptions and reconnects without fail including on network disconnects...
It has been extremely stable and reliable and eliminates logs every 10 seconds while disconnected.
This component can also be used bi-directionally with multiple systems being both masters and slaves...
This should be done as a pull request if I had the time to learn how to do that...

    self._connection = None
    self._entities = set()
    self._handlers = {}
    self._remove_listener = None
    self._remove_entities = True

    self._instance_attrs = {
        'entity_prefix': self._entity_prefix,
        'host': self._host,
        'port': self._port,
        'secure': self._secure,
        'verify_ssl': self._verify_ssl
    }

    self._entities.add(self._connection_state_entity)
    self._hass.states.async_set(self._connection_state_entity, STATE_CONNECTING, self._instance_attrs)

    self.__id = 1

def _prefixed_entity_id(self, entity_id):
    if self._entity_prefix:
        domain, object_id = split_entity_id(entity_id)
        object_id = self._entity_prefix + object_id
        entity_id = domain + '.' + object_id
        return entity_id
    return entity_id

@callback
def _full_url(self):
    """Full url for connection."""
    return '%s://%s:%s/api/websocket' % (
        'wss' if self._secure else 'ws', self._host, self._port)

@callback
def _short_url(self):
    """Short url for display."""
    return '%s://%s:%s' % (
        'wss' if self._secure else 'ws', self._host, self._port)

async def async_connect(self):
    """Connect to remote HA websocket..."""
    url = self._full_url()
    urld = self._short_url()

    session = async_get_clientsession(self._hass, self._verify_ssl)
    conn_err = False
    self._hass.states.async_set(self._connection_state_entity, STATE_CONNECTING, self._instance_attrs)

    while True:
        try:
            _LOGGER.info('Connecting to %s', urld)
            self._connection = await session.ws_connect(url)
        except aiohttp.client_exceptions.ClientError as err:
            if not conn_err:
                _LOGGER.error(
                    'Could not connect to %s, retry every 10 seconds...', urld)
            conn_err = True
            self._hass.states.async_set(self._connection_state_entity, STATE_RECONNECTING, self._instance_attrs)
            await asyncio.sleep(10)
        else:
            _LOGGER.info(
                'Connected to HA websocket at %s', urld)
            self._hass.states.async_set(self._connection_state_entity, STATE_CONNECTED, self._instance_attrs)
            break

    async def stop():
        """Close connection."""
        if self._connection is not None:
            _LOGGER.error('Websocket connection at %s closing...', urld)
            await self._connection.close()
        self._hass.states.async_set(self._connection_state_entity, STATE_DISCONNECTED)

    self._hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STOP, stop)

    asyncio.ensure_future(self._recv())

def _next_id(self):
    _id = self.__id
    self.__id += 1
    return _id

async def _call(self, callback, message_type, **extra_args):
    _id = self._next_id()
    self._handlers[_id] = callback
    try:
        await self._connection.send_json(
            {'id': _id, 'type': message_type, **extra_args})
    except aiohttp.client_exceptions.ClientError as err:
        _LOGGER.error('Remote websocket connection closed: %s', err)
        await self._disconnected()

async def _disconnected(self):
    if self._remove_entities:
        # Remove all published entries
        for entity in self._entities:
            self._hass.states.async_remove(entity)
    if self._remove_listener is not None:
        self._remove_listener()
    self._remove_listener = None
    if self._remove_entities:
        self._hass.states.async_set(self._connection_state_entity, STATE_DISCONNECTED)
        self._entities = set()
    self._remove_entities = True
    asyncio.ensure_future(self.async_connect())

async def _recv(self):
    """Retreive data from remote instance."""

    while not self._connection.closed:
        try:
            data = await asyncio.wait_for(self._connection.receive(), 30)
        except aiohttp.client_exceptions.ClientError as err:
            _LOGGER.error('Remote websocket connection closed: %s', err)
            break
        except:
            _LOGGER.error('Websocket connection lost...')
            await self._connection.close()
            break

        if not data:
            break

        if data.type in (aiohttp.WSMsgType.CLOSE, aiohttp.WSMsgType.CLOSED):
            _LOGGER.error('Websocket connection is closing...')
            break

        if data.type == aiohttp.WSMsgType.ERROR:
            _LOGGER.error('Websocket connection had an error...')
            break

        try:
            message = data.json()
        except TypeError as err:
            _LOGGER.error('Could not decode data (%s) as json: %s', data, err)
            break

        if message is None:
            break

        _LOGGER.debug('Received: %s', message)

        if message['type'] == api.TYPE_AUTH_OK:
            await self._init()

        elif message['type'] == api.TYPE_AUTH_REQUIRED:
            if not (self._access_token or self._password):
                _LOGGER.error('Access token or api password required, but not provided')
                return
            if self._access_token:
               data = {'type': api.TYPE_AUTH, 'access_token': self._access_token}
            else:
               data = {'type': api.TYPE_AUTH, 'api_password': self._password}
            try:
               await self._connection.send_json(data)
            except Exception as err:
               _LOGGER.error('Could not send data to remote connection: %s', err)
               break

        elif message['type'] == api.TYPE_AUTH_INVALID:
            _LOGGER.error('Auth invalid, check your access token or API password')
            await self._connection.close()
            return

        else:
            callback = self._handlers.get(message['id'])
            if callback is not None:
                try:
                   callback(message)
                except:
                   await self._connection.close()
                   self._remove_entities = False
                   break

    await self._disconnected()

async def _init(self):

**Comment by postlund** [comment]
@jacekpaszkowski Can you try if #80 works better?

@jacekpaszkowski A lot has changed since that code applied, you are probably the best one to port it to the new code as you understand how it works. But as you say, a PR is the only way to move forward. It's to tedious to deal with code changes like this.

**Comment by jacekpaszkowski** [comment]
@postlund yes, i can confirm that it works ok. I've tested this by unplugging network cable from "master" device. Please see the logs below:

```
2020-12-09 11:20:28 ERROR (MainThread) [custom_components.remote_homeassistant] heartbeat failed
2020-12-09 11:20:29 ERROR (MainThread) [custom_components.remote_homeassistant] heartbeat failed

2020-12-09 11:20:34 ERROR (MainThread) [custom_components.remote_homeassistant] failed to fetch instance info
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1005, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 871, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 366, in _async_instance_get_info
    return await async_get_discovery_info(
  File "/config/custom_components/remote_homeassistant/rest_api.py", line 38, in async_get_discovery_info
    async with session.get(url, headers=headers) as resp:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1124, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 527, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 541, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 898, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1017, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio-slave1-wifi.lan:8123 ssl:default [Try again]
2020-12-09 11:20:34 INFO (MainThread) [custom_components.remote_homeassistant] Connecting to ws://hassio-slave1-wifi.lan:8123/api/websocket
2020-12-09 11:20:34 ERROR (MainThread) [custom_components.remote_homeassistant] failed to fetch instance info
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1005, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 871, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 366, in _async_instance_get_info
    return await async_get_discovery_info(
  File "/config/custom_components/remote_homeassistant/rest_api.py", line 38, in async_get_discovery_info
    async with session.get(url, headers=headers) as resp:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1124, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 527, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 541, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 898, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1017, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio-slave2-wifi.lan:8123 ssl:default [Try again]
2020-12-09 11:20:34 INFO (MainThread) [custom_components.remote_homeassistant] Connecting to ws://hassio-slave2-wifi.lan:8123/api/websocket

2020-12-09 11:20:42 ERROR (MainThread) [custom_components.remote_homeassistant] Could not connect to ws://hassio-slave1-wifi.lan:8123/api/websocket, retry in 10 seconds...
2020-12-09 11:20:42 ERROR (MainThread) [custom_components.remote_homeassistant] Could not connect to ws://hassio-slave2-wifi.lan:8123/api/websocket, retry in 10 seconds...

2020-12-09 11:20:57 ERROR (MainThread) [custom_components.remote_homeassistant] failed to fetch instance info
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1005, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 871, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 366, in _async_instance_get_info
    return await async_get_discovery_info(
  File "/config/custom_components/remote_homeassistant/rest_api.py", line 38, in async_get_discovery_info
    async with session.get(url, headers=headers) as resp:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1124, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 527, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 541, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 898, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1017, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio-slave1-wifi.lan:8123 ssl:default [Try again]
2020-12-09 11:20:57 INFO (MainThread) [custom_components.remote_homeassistant] Connecting to ws://hassio-slave1-wifi.lan:8123/api/websocket
2020-12-09 11:20:57 ERROR (MainThread) [custom_components.remote_homeassistant] failed to fetch instance info
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1005, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 871, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 366, in _async_instance_get_info
    return await async_get_discovery_info(
  File "/config/custom_components/remote_homeassistant/rest_api.py", line 38, in async_get_discovery_info
    async with session.get(url, headers=headers) as resp:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1124, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 527, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 541, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 898, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1017, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio-slave2-wifi.lan:8123 ssl:default [Try again]
2020-12-09 11:20:57 INFO (MainThread) [custom_components.remote_homeassistant] Connecting to ws://hassio-slave2-wifi.lan:8123/api/websocket

2020-12-09 11:20:59 ERROR (MainThread) [custom_components.remote_homeassistant] Could not connect to ws://hassio-slave1-wifi.lan:8123/api/websocket, retry in 10 seconds...
2020-12-09 11:20:59 ERROR (MainThread) [custom_components.remote_homeassistant] Could not connect to ws://hassio-slave2-wifi.lan:8123/api/websocket, retry in 10 seconds...

[....]

2020-12-09 11:21:09 INFO (MainThread) [custom_components.remote_homeassistant] Connecting to ws://hassio-slave1-wifi.lan:8123/api/websocket
2020-12-09 11:21:09 INFO (MainThread) [custom_components.remote_homeassistant] Connected to home-assistant websocket at ws://hassio-slave1-wifi.lan:8123/api/websocket

2020-12-09 11:21:11 INFO (MainThread) [custom_components.remote_homeassistant] Connecting to ws://hassio-slave2-wifi.lan:8123/api/websocket
2020-12-09 11:21:11 INFO (MainThread) [custom_components.remote_homeassistant] Connected to home-assistant websocket at ws://hassio-slave2-wifi.lan:8123/api/websocket

``

**Comment by postlund** [comment]
@jacekpaszkowski Great, thanks for testing so quickly! 👍

@lukas-hetzenecker Since #80 improves the situation, we should be ready to merge that.

**Comment by matata86** [comment]
Hi, thank for your hard work!
I trying #80 ... but if I restart remote instance HA, all remote entities are unavailable and dont reconnect... :-/

**Comment by jacekpaszkowski** [comment]
@postlund i can also confirm there is a problem after restarting "slave" HA instance. @matata86 is right.
Reloading integration or restarting "master" HA fixes the issue.

**Comment by jacekpaszkowski** [comment]
also i've just found another error which causes that #80 version doesn't reconnect:

```
2020-12-09 16:54:49 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/adaptive_lighting/switch.py", line 885, in _light_event
    if await self.turn_on_off_listener.maybe_cancel_adjusting(
  File "/config/custom_components/adaptive_lighting/switch.py", line 1375, in maybe_cancel_adjusting
    id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'

2020-12-09 16:55:51 ERROR (MainThread) [custom_components.remote_homeassistant] could not send data to remote connection: Cannot write to closing transport
2020-12-09 16:55:51 ERROR (MainThread) [custom_components.remote_homeassistant] could not send data to remote connection: Cannot write to closing transport
```

**Comment by postlund** [comment]
I will try to replicate if possible later tonight and see if I can fix that.

**Comment by jaym25** [comment]
If you look at my comment at the end of issue "remote home assistant slave devices not connected automatically after WAN outage"  The code pasted properly there.  I am not having any problem with the slave reconnecting and I am using it bidirectionally over SSL internet with locations that are miles apart.

**Comment by postlund** [comment]
@jacekpaszkowski @matata86 I pushed a few updates, please give it a try. Should work better now.

**Comment by matata86** [comment]
@postlund YES, it works for me... Awesome. Thank you.

**Comment by jacekpaszkowski** [comment]
@postlund works much better. Also after "slave" restart component reconnects. Thank You!

**Comment by jaym25** [comment]
@postlund I am finding that when the slave network is disconnected and reconnected, the entities reconnect.  However, when the slave is restarted, the entities do not come back.  This is happening in both directions since I am using both as masters and slaves.  i.e.  when I restart one unit the other does not recover it's remote entities and vice versa.  Below are the errors from one master:

2020-12-09 19:12:33 ERROR (SyncWorker_3) [homeassistant.components.nut] Failure getting NUT ups alias, Socket error.
2020-12-09 19:14:40 ERROR (MainThread) [custom_components.remote_homeassistant] heartbeat failed
2020-12-09 19:16:20 ERROR (MainThread) [custom_components.remote_homeassistant] heartbeat failed
2020-12-09 19:18:01 ERROR (MainThread) [custom_components.remote_homeassistant] heartbeat failed
2020-12-09 19:18:34 ERROR (MainThread) [custom_components.remote_homeassistant] failed to fetch instance info
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore # noqa
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
return await fut
File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('xxx.xxx.xxx.xxx', 443)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/remote_homeassistant/__init__.py", line 366, in _async_instance_get_info
return await async_get_discovery_info(
 File "/config/custom_components/remote_homeassistant/rest_api.py", line 38, in async_get_discovery_info
async with session.get(url, headers=headers) as resp:
File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1124, in __aenter__
self._resp = await self._coro
File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 527, in _request
conn = await self._connector.connect(
File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 541, in connect
proto = await self._create_connection(req, traces, timeout)
File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 898, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1057, in _create_direct_connection
raise last_exc
File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1026, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 981, in _wrap_create_connection
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host xxx.xxx.com:443 ssl:default [Connect call failed ('xxx.xxx.xxx.xxx', 443)]
2020-12-09 19:18:34 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/remote_homeassistant/__init__.py", line 399, in async_connect
if not (info or _async_instance_id_match(info)):
 File "/config/custom_components/remote_homeassistant/__init__.py", line 381, in _async_instance_id_match
if info["uuid"] != self._entry.unique_id:
TypeError: 'NoneType' object is not subscriptable

**Comment by jaym25** [comment]
I don't know if you reviewed my code from previous comments, but this is one of the problems I had solved...

**Comment by jaym25** [comment]
@postlund - I also found that reloading the integration on the master restores the remote entities.  Thank

**Comment by jaym25** [comment]
@postlund - Flipping a remote switch on the master is disconnecting all the other entities.  Once again, reloading the integration restores all.
Looks like I will revert to my custom 2.3 for now.

**Comment by lukas-hetzenecker** [comment]
New release published.
Please reopen this issue, if you still get any disconnects/errors with the new release.
